version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    
    networks:
      - django_db_net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/django_db
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - django_db_net
      - django_pgadmin_net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - django_pgadmin_net

networks:
  django_db_net:      
  django_pgadmin_net: 

volumes:
  postgres_data:
